### ISSUE TITLE
Possible optimizations using buffer split?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/tabix-js#10]
Some of the time spent converting to string seems to take some time on large files. I don't know exactly how to attack the issue but I saw that for example split operation directly on the buffer can take place https://github.com/maxogden/binary-split

**Comment by garrettjstevens** [comment]
Makes sense to me. If we delay `.toString()` until `getLines()` and do it on a line at a time we can avoid converting lines that end up not getting used.

**Comment by cmdcolin** [comment]
jrobinson also said possibly avoiding a split('\n') might be helpful

**Comment by rbuels** [comment]
Just as long as any optimizations are based on real data from the profiler.

**Comment by cmdcolin** [comment]
It does not pop out immediately in CPU profiling but it makes a very high memory usage change

```
Before split memory usage 11.77 MB
After split: memory used 312.3 MB
```

That's before/after the convert to string and split in readChunk, after requesting a fairly large chunk of 1000 genomes data.

**Comment by cmdcolin** [comment]
```
      let used = process.memoryUsage().heapUsed / 1024 / 1024;
      console.log(`Before split memory usage ${Math.round(used * 100) / 100} MB`);
      const lines = uncompressed.toString('utf8').split('\n')

      used = process.memoryUsage().heapUsed / 1024 / 1024;
      console.log(`After split: memory used ${Math.round(used * 100) / 100} MB`);

```

**Comment by cmdcolin** [comment]
We'll close this because we found that doing this results in slowdown. Instead we still decode text of the chunk but just do 1 chunk at a time

**Comment by cmdcolin** [comment]
If browser had a super fast text convert it might be ok but for now keep as is
