### ISSUE TITLE
v1.4.5 does not work in the browser

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/tabix-js#101]
After 5a3e958c4bf27cbf3e935c577dfb8fd3210c561f, tabix-js does not work in the browser:

![image](https://user-images.githubusercontent.com/25592344/80668589-81a7b780-8a5f-11ea-84ee-a540d45b43aa.png)

In my testing, `unzip` in node works fine, but in the browser it returns `undefined`, which throws the 'length' error above when the code tries to read `bytes.length`. Seems like a difference between pako and node unzipping?

https://github.com/GMOD/tabix-js/blob/c321e168d8ec12a76200ca7205560f88e66c735c/src/tabixIndexedFile.ts#L269-L276

**Comment by cmdcolin** [comment]
Darn, thanks for catching

**Comment by garrettjstevens** [comment]
Cool, glad this could get resolved without having to revert back to `stat`.

**Comment by cmdcolin** [comment]
1.4.6 published :)
