### ISSUE TITLE
Dealing with big remote files

### ISSUE THREAD

**Issue by bommox** [GMOD/tabix-js#128]
Hi,

I've just been trying the examples with the 1000g phase3 dataset (http://ftp.ensembl.org/pub/release-104/variation/vcf/homo_sapiens/)

- With the VCF and CSI in my local machine, it works really fast.
- But when using the remoteFile utility (from your other library generic-filehandle) it takes forever...

```
const {TabixIndexedFile} = require('@gmod/tabix')
const {RemoteFile} = require('generic-filehandle')
const fetch = require('node-fetch')

const log = console.log;

const URL = 'http://ftp.ensembl.org/pub/release-104/variation/vcf/homo_sapiens/1000GENOMES-phase_3.vcf.gz';

const remoteIndexed = new TabixIndexedFile({
  filehandle: new RemoteFile(URL, {fetch}),
  csiFilehandle: new RemoteFile(URL + '.csi', {fetch})
});

remoteIndexed.getHeader().then(log)  //<-- This doesn't resolve. Also getLines does not work.
```

Am I doing something wrong?

Thanks!

**Comment by cmdcolin** [comment]
There may be a bug with either our library, maybe particularly with CSI file extensions or with how ensembl is responding to our http range requests maybe
This example app for example has big troubles and says "Error: invalid distance too far back"

https://codesandbox.io/s/keen-khorana-3synw?file=/src/App.js
direct link to contents of codesandbox
https://3synw.csb.app/


are you saying it works locally for you in nodejs? i am not sure if i can get it to work locally in node for me ither

**Comment by cmdcolin** [comment]
interestingly it works fine in jbrowse 2 loaded as a track...might be missing something still

**Comment by cmdcolin** [comment]
there may be something particular about codesandbox here that is making it fail which is very weird... I can run the same code from the codesandbox as a independently deployed CRA app and it works fine


https://github.com/cmdcolin/cra_tabix_testing
https://cmdcolin.github.io/cra_tabix_testing/

this is pretty weird, but also, not sure if it helps with the problem you refer to or not! let me know if you have any more details that maybe we can try to help with

note that I changed the URL to https from http because it is better for CORS that way

**Comment by bommox** [comment]
Hi @cmdcolin , thanks for your tests.

I have tested locally from nodeJs and fails using that URL.
But with another https remoteFile works fine! same script! so probably has something to do with the http protocol that ensembl is using for exposing their ftp...


For instance: https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/dbsnp_138.b37.vcf.gz 

works well, same script.

**Comment by cmdcolin** [comment]
interesting! weird stuff. if you think it's something like a bug in this library let me know...

**Comment by bommox** [comment]
No, now I think it's not. Thanks!
