### ISSUE TITLE
Typescript compilation errors in generic-filehandle module

### ISSUE THREAD

**Issue by gokhalesujit** [GMOD/tabix-js#141]
Installed latest library version - 1.5.11 and getting following typescript compilation errors. Please advise.

> tsc

node_modules/generic-filehandle/dist/filehandle.d.ts:2:31 - error TS2304: Cannot find name 'RequestInfo'.

2 export type Fetcher = (input: RequestInfo, init?: RequestInit) => Promise<PolyfilledResponse>;
                                ~~~~~~~~~~~

node_modules/generic-filehandle/dist/filehandle.d.ts:2:51 - error TS2304: Cannot find name 'RequestInit'.

2 export type Fetcher = (input: RequestInfo, init?: RequestInit) => Promise<PolyfilledResponse>;
                                                    ~~~~~~~~~~~

node_modules/generic-filehandle/dist/filehandle.d.ts:8:45 - error TS2304: Cannot find name 'Response'.

8 export interface PolyfilledResponse extends Response {
                                              ~~~~~~~~

node_modules/generic-filehandle/dist/remoteFile.d.ts:11:18 - error TS2304: Cannot find name 'RequestInfo'.

11     fetch(input: RequestInfo, init: RequestInit | undefined): Promise<PolyfilledResponse>;
                    ~~~~~~~~~~~

node_modules/generic-filehandle/dist/remoteFile.d.ts:11:37 - error TS2304: Cannot find name 'RequestInit'.

11     fetch(input: RequestInfo, init: RequestInit | undefined): Promise<PolyfilledResponse>;
                                       ~~~~~~~~~~~


Found 5 errors in 2 files.

Errors  Files
     3  node_modules/generic-filehandle/dist/filehandle.d.ts:2
     2  node_modules/generic-filehandle/dist/remoteFile.d.ts:11

**Comment by cmdcolin** [comment]
you can maybe add

skipLibCheck:true to your tsconfig.json, or add "dom" to compilerOptions.lib, 

Example tsconfig.json that I sometimes use as a template

```json
{
  "include": ["src"],
  "compilerOptions": {
    "outDir": "dist",
    "target": "es2018",
    "lib": ["dom", "esnext"],
    "types": ["node"],
    "declaration": true,
    "moduleResolution": "node",
    "strict": true,
    "esModuleInterop": true
  }
}
```

**Comment by gokhalesujit** [comment]
Thank you Colin! Adding "dom" to compilerOptions.lib did the trick.
