### ISSUE TITLE
How to include tabix-js directly in html

### ISSUE THREAD

**Issue by bw2** [GMOD/tabix-js#146]
Hi, would it be possible to build a single minified tabix-js source and make it available via CDN so it can be added to an html page   without requiring an npm build?

**Comment by cmdcolin** [comment]
currently we don't have a single minified source for tabix. we do have one for cram-js though so we could consider making one for tabix....

**Comment by bw2** [comment]
thanks. I would like to use it on [spliceai-lookup](https://spliceailookup.broadinstitute.org/).

**Comment by cmdcolin** [comment]
i copied the cram approach here in this PR https://github.com/GMOD/tabix-js/pull/147

there is a gzip download example. it is a "UMD" bundle that sets a variable called "gmodTABIX"

an example source code using it 


```
<html>
  <head>
    <script src="tabix-bundle.js"></script>
    <script type="text/javascript">
      ;(async () => {
        const { TabixIndexedFile } = window.gmodTABIX

        const tbiIndexed = new TabixIndexedFile({
          url: 'yourfile.vcf.gz',
          tbiUrl: 'yourfile.vcf.gz.tbi',
        })
        const lines = []
        await tbiIndexed.getLines('ctgA', 0, 10000, line =>
          lines.push(line),
        )
        document.getElementById('output').innerHTML = lines.join('\n')
      })()
    </script>
  </head>
  <body>
    <h1>Hello world</h1>
    <pre id="output" />
  </body>
</html>
```

misc note: note that url and tbiUrl were added on this branch, not on master currently. that avoids needing to bundle a separate generic-filehandle bundle.



attachment:
[tabix-bundle.js.gz](https://github.com/user-attachments/files/16514682/tabix-bundle.js.gz)
is like this

**Comment by cmdcolin** [comment]
(note that if something like that works for you, then we can merge and then it can be available from the unpkg cdn which hosts stuff that is published on npm)

**Comment by bw2** [comment]
Thanks for the quick response and example!   
I'm able to run the test example. 

Ps. Currently, when I try to point it at a tabixed text file in a public google storage  bucket, I get a CORS error. 
<img width="589" alt="image" src="https://github.com/user-attachments/assets/4e1346ec-f4c7-4dff-b2d3-f584709a32a1">
<img width="564" alt="image" src="https://github.com/user-attachments/assets/264ce982-1178-47b9-aea2-b2a03e7d394b">

even though the data file and tabix index exist.

I will see if I can troubleshoot this. For now, I've tried running

gcloud storage buckets update gs://spliceai-lookup-reference-data

[
    {
      "origin": ["*"],
      "method": ["GET"],
      "responseHeader": ["Content-Type"],
      "maxAgeSeconds": 3600
    }
]

but still get the error.

**Comment by cmdcolin** [comment]
CORS errors are tricky. it generally comes down to a server side config. if you responseHeader is something related to cors you might also need to enable Content-Length and Content-Range...this is an example we use for amazon s3 buckets https://jbrowse.org/docs/cors.html

it is a little more detailed than a typical cors config due to the need for content-length (might be skippable in some cases) and ranges (requires)

**Comment by bw2** [comment]
It works! I needed to change the url from 
```
https://storage.cloud.google.com/bucket-name/file.bed.gz
```
to 
```
https://storage.googleapis.com/bucket-name/file.bed.gz
```
Thanks again for your help!

The google bucket CORS config I'm using now is 
```
[
    {
	"origin": ["*"],
	"method": ["GET","POST","HEAD"],
	"responseHeader": ["*"],
	"maxAgeSeconds": 3600,
    }
]
```
and I set it by running
```
gsutil cors set config.json  gs://bucket-name
```

**Comment by cmdcolin** [comment]
went ahead and merged this PR, you can now get it remotely from remote CDN like unpkg  (if interested...certainly can download and vendor it also)

latest https://unpkg.com/@gmod/tabix/dist/tabix-bundle.js
specific version https://unpkg.com/@gmod/tabix@1.5.15/dist/tabix-bundle.js

let me know if you run into any issues :)

**Comment by bw2** [comment]
thanks!
