### ISSUE TITLE
Mysterious typing issue in `.d.ts` files.

### ISSUE THREAD

**Issue by tuner** [GMOD/tabix-js#149]
Hi,

I'm not sure if this qualifies as bug, but perhaps you have some idea what's going on...

The typings of the latest release (`v1.6.0`) use `Buffer` with generics:

`getHeaderBuffer(opts?: Options): Promise<Buffer<Uint8Array<ArrayBuffer>>>;` (https://cdn.jsdelivr.net/npm/@gmod/tabix@1.6.0/esm/tabixIndexedFile.d.ts)

... while previous releases (such as `v1.5.15`) do not:

`getHeaderBuffer(opts?: Options): Promise<Buffer>;`(https://cdn.jsdelivr.net/npm/@gmod/tabix@1.5.15/esm/tabixIndexedFile.d.ts)

However, typings of the Buffer package do not support any kind of generic types:
`export class Buffer extends Uint8Array { ...` (https://github.com/feross/buffer/blob/master/index.d.ts)

Obviously, `tsc` is unhappy about this when I'm trying to use the latest release. The `skipLibCheck` option might suppress the error, but it has some other unfortunate side effects.

I tried to understand what has changed between `v1.5.15` and `v1.6.0` but couldn't find a culprit. Moreover, I recompiled `v1.5.15` and guess what, `esm/tabixIndexedFile.d.ts` has a generic parameter in Buffer 🤯.

**Comment by cmdcolin** [comment]
this was a thing that was inroduced in I believe typescript 5.7

I did not investigate it deeply but i think it is related to changes typescript made. You can maybe downgrade to typescript ~5.6.x to fix it (jbrowse does this currently)

This whole thing also gave me a bit of a kick in the pants to maybe try to get rid of our usage of the Buffer polyfill, so i started a PR here in generic-filehandle to try to start that process

https://github.com/GMOD/generic-filehandle/pull/114

it will take some time before that gets traction but i think it might be best for the long run to remove our use of Buffer

**Comment by cmdcolin** [comment]
actually sorry that linked jbrowse issue is a somewhat different typescript issue.

https://github.com/GMOD/generic-filehandle/pull/114


 It's possible the 5.6 downgrade would still help but the only thing that hints at this issue is a footnote in the ("I saw that typescript 5.8 (next) was making an error at some of the Buffer types")

**Comment by cmdcolin** [comment]
and actually, I now see you mention that OUR types that are outputted from the tabix-js library were changed. this is indeed probably related to tabix-js upgrading to typescript 5.7 which changed the way that they output type definitions!

I could probably revert that change too for now to help with this..

**Comment by cmdcolin** [comment]
I published @gmod/tabix@1.6.1 with downgraded typescript 5.6 for fixed .d.ts generation ...this should help with not outputting "Buffer generics"

**Comment by cmdcolin** [comment]
note @gmod/bgzf-filehandle also needed the same treatment

**Comment by tuner** [comment]
Thanks Colin! Seems to work 🥳
