### ISSUE TITLE
Promise as line handler

### ISSUE THREAD

**Issue by ArturPrzybysz** [GMOD/tabix-js#29]
As in title:
```js
const tbiIndexed = new TabixIndexedFile({
  filehandle: new BlobFile(gzFile),
  tbiFilehandle: new BlobFile(tabixFile)
});
const refNames = await tbiIndexed.getReferenceSequenceNames();

await tbiIndexed.getLines(refName, 100, 200, hopefullyAPromise);
```

Is there any possibility for `getLines` to use Promises as line handlers?

**Comment by rbuels** [comment]
I'm a little confused, what would getLines do to the promise to emit lines?

**Comment by ArturPrzybysz** [comment]
@rbuels wait for the promise to resolve or reject before firing line handler for a next line

**Comment by cmdcolin** [comment]
It seems to me that you could maybe work around this in your app, it would be difficult or maybe awkward to add this to tabix

```
//first collect lines
const lines = []
await getLines(refName,100,200,line=> lines.push(line))
//then process them
for(var i = 0; i < lines.length; i++) { await doSomethingToLineThatReturnsPromise(lines[i]) }
```

Does that make sense or is there something that would prevent that from working?

**Comment by ArturPrzybysz** [comment]
@cmdcolin It is a reasonable approach, thanks.

**Comment by ArturPrzybysz** [comment]
I will experiment with async.queue, perhaps it will be more graceful than straight up line buffering.

**Comment by cmdcolin** [comment]
That sounds pretty reasonable for if there is large data. You can start processing the lines instantly and add some stuff to a promise queue or something similar

```
const PQueue = require('p-queue');
const pq = new PQueue({concurrency: 1});

await getLines(refName,100,200,line=> pq.push(fetch(`http://google.com/?q=${line}`)))
await pq.onEmpty();
```

**Comment by ArturPrzybysz** [comment]
Sorry for deleting my post about async.queue. I thought its not related with GMOD and it should not be here.

Thank you for help!
