### ISSUE TITLE
File offset and newline questions

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/tabix-js#3]
Hey @rbuels, not sure if this is really an issue, maybe I just don't understand what's going on. When you calculate the file offset for the line callback, it's calculated like this:
https://github.com/GMOD/tabix-js/blob/36f6adb947f5be7caef1afc3b6881e3261e08e50/src/tabixIndexedFile.js#L126-L127
and then the current start is updated like this
https://github.com/GMOD/tabix-js/blob/36f6adb947f5be7caef1afc3b6881e3261e08e50/src/tabixIndexedFile.js#L153

My question is, won't that not be accurate as the file offset since the line no longer has the newline character?

Also, related to the newline character, technically VCF supports LF and CRLF line endings, so this
https://github.com/GMOD/tabix-js/blob/36f6adb947f5be7caef1afc3b6881e3261e08e50/src/tabixIndexedFile.js#L365
might need to be something like
```js
const lines = uncompressed.toString('utf8').split(/\r?\n/)
```

**Comment by rbuels** [comment]
These are all correct observations, good catch! I'll fix those things.

**Comment by rbuels** [comment]
that patch just adds 1 to the line start and trims the line before emitting it, so that we don't have to keep track of whether the line had CRLF or just LF

**Comment by rbuels** [comment]
published fix as v1.1.1
