### ISSUE TITLE
How to determine that block is over?

### ISSUE THREAD

**Issue by ArturPrzybysz** [GMOD/tabix-js#38]
So far I used your library like this:
```
    const refNames = await tbiIndexed.getReferenceSequenceNames();
    const step = 1e6;
    for (let refName of refNames) {
      let i = 0;
      while (true) {
        try {
          await tbiIndexed.getLines(refName, i, i + step, lineHandler);
        } catch (e) {
          break;  // when an exception is caught I go to next refName, but for some files it does not happen
        }
        i += step;
      }
    }
```
Not a very elegant way, but it works if I want to make a pass over all lines in sequence. I have noticed, that when block is out of lines, there is thrown exception (string of value `"Cannot read property 'compareTo' of undefined"`).
I believe that it is not an intended use of this method.

However, I have stumbled upon some file, which do not trigger such exception and the loop goes    on forever.

Could you advise me on how to overcome such problem? How could I know, that there is no more lines to query?

I have tried to look into `tbiIndexed.getMetadata()` method, but its result did not said much to me.

**Comment by garrettjstevens** [comment]
Can I ask what version of tabix-js you're using? The fact that you're getting an exception at all seems odd, I would expect your code to loop infinitely. If you have any data to share that reproduces the problem, too, that would be great.

There is a feature pending release that would allow you to have `end` be undefined, so you could use

```js
tbiIndexed.getLines(refName, 0, undefined, lineCallback)
```

to work on every line in `refName`. Would that satisfy your use case?

**Comment by ArturPrzybysz** [comment]
@garrettjstevens 
From my package.json
```
    "@gmod/bgzf-filehandle": "^1.2.4",
    "@gmod/tabix": "^1.1.5",
    "generic-filehandle": "latest",
```
This behavior occurs in all of my files, except for just one, so I believe there is a high chance, that any other files would reproduce the problem. 

Yeah, this would be amazing. Is there a way to stop iteration?
When is it going to be released?

**Comment by garrettjstevens** [comment]
@ArturPrzybysz, I tried on several different files and never could replicate what you saw. All my tests just looped infinitely on the first refName and never threw an error.

The change should be released after #37 is merged, so probably soon. I'm not sure what you mean about stopping the iteration, though.

**Comment by ArturPrzybysz** [comment]
@garrettjstevens

> I'm not sure what you mean about stopping the iteration, though.

I thought about possibility `break` out of getLines, after checking something in the callback. In a case that I don't know exactly when I want to end iteration over lines and its being determined on the run.

**Comment by garrettjstevens** [comment]
The open-ended query feature I talked about has been released in v1.2.0 of `@gmod/tabix`.

As of now, there is no way to stop the iteration, but I added a feature request for that in https://github.com/GMOD/tabix-js/issues/41.

**Comment by garrettjstevens** [comment]
@ArturPrzybysz It turns out you can break out of the iteration early by throwing an error. Here's an example:

```js
async function finder(thing) {
  const f = new TabixIndexedFile({
    path: require.resolve('my.vcf.gz'),
    tbiPath: require.resolve('my.vcf.gz.tbi'),
  })
  let entry
  try {
    await f.getLines('chr1', 0, undefined, line => {
      if (line.includes(thing)) {
        entry = line
        throw new Error('found it')
      }
    })
  } catch (e) {
    // Found the thing
  }
  return entry
}
```

Thanks to @rbuels for pointing this out in #41.

**Comment by ArturPrzybysz** [comment]
Thats great, thank you for the example and letting me know!
