### ISSUE TITLE
Variants with symbolic ALT and length defined by INFO END not getting queried

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/tabix-js#4]
This happens when the ALT is symbolic and the length of the variant is defined by END in the INFO field. For example:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
22	16050654	.	A	<CN3>	.	PASS	SVTYPE=CNV;END=16063474
```
The failing test is:
```js
it('can fetch a CNV with length defined by END in INFO field', async () => {
  const f = new TabixIndexedFile({
    path: require.resolve('./data/CNVtest.vcf.gz'),
  })

  const lines = new RecordCollector()
  await f.getLines('22', 16063470, 16063480, lines.callback)
  expect(lines.length).toEqual(1)
})
```
I checked and the `tabix` command line utility does retrieve this variant with this same VCF and index:
```
$ tabix CNVtest.vcf.gz 22:16063470-16063480 | wc -l
1
```

EDIT: you can find this failing test and the VCF/TBI in the `cnv_query` branch.

**Comment by rbuels** [comment]
Oh I bet this is related to the post-filtering of the features after
getting them from the blocks, probably needs to filter differently if doing
vcf
