### ISSUE TITLE
Enhancement: Stop iterating getLines

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/tabix-js#41]
Feature request from #38 

From what I understand, the idea is that perhaps you're iterating over lines with getLines and looking for something. When you find it, you want to be able to stop the getLines iteration to save time.

Possible implementation: watch for a certain value to be returned by the lineHandler callback, and stop the iteration if that value is returned.

**Comment by rbuels** [comment]
I think, but I haven't tested this, that a user could stop iteration by
throwing a special early-stop exception inside the line handler callback.
That should make the returned promise reject, and a user could catch it
with a `catch` handler on the promise.

If that technique works, we wouldn't need to add any more functionality for
that scenario.

**Comment by garrettjstevens** [comment]
I tested and it works. Good call!
