### ISSUE TITLE
fileOffset not correct when non-ascii characters are present

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/tabix-js#7]
Because the code uses `line.length` to advance the fileOffset, it doesn't advance enough when there are non-ascii characters, since their byte length is longer than their string length.

See failing test for this in the non_ascii branch.

**Comment by cmdcolin** [comment]
Closed from #8 ...if it is an issue maybe reopen

**Comment by cmdcolin** [comment]
(note that I revisited this because the fileOffset based calcs are on jbrowse master now)
